export const LOAD_PHOTOS_SUCCESS = 'LOAD_PHOTOS_SUCCESS';
export const SET_PHOTO = 'SET_PHOTO';
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';